spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.221.121.240:1521/cicop
    username: system
    password: tim@1234
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect